name: Build and Deploy YangSpaceApp

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0 # Use the version your project targets

    # Step 3: Setup Node.js for Angular
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Use the Node.js version your Angular app requires

    # Step 4: Build Angular app
    - name: Build Angular App
      working-directory: yangspaceapp.client/
      run: |
        npm install
        npm run build -- --configuration production

    # Step 5: Move Angular output to ASP.NET Core wwwroot
    - name: Copy Angular Build to wwwroot
      run: |
        mkdir -p YangSpaceApp.Server/wwwroot
        cp -R YangSpaceApp.Client/dist/browser/* YangSpaceApp.Server/wwwroot/

    # Step 6: Publish ASP.NET Core app
    - name: Publish ASP.NET Core App
      working-directory: YangSpaceApp.Server/
      run: |
        dotnet publish -c Release -o ./publish

    # Step 7: Deploy to Azure
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: <yangspace> # Replace with your App Service name
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: YangSpaceApp.Server/publish
